#!/bin/bash
# kernal - The SimulOS kernal.

# Initialize the kernel.
function initKrn() {
  krnLog "Kernel init..."
  # TODO: Add some more code here.
  krnLog "Kernel init done."
}

# Log the first argument to the kernel log.
function krnLog() {
  echo $1 > $hardDrive/system/logs/kernel.log
}

# TODO: Figure out what should go in here and what should go in SysCall.lib.
