#!/bin/bash
# kernal - The SimulOS kernal.

# Initialize the kernel.
function initKrn() {
  krnLogInit
  krnLog "Kernel init..."
  initVfs
  # TODO: Add some more code here.
  krnLog "Kernel init done."
}

function initVfs() {
  krnLog "Initializing virtual file system..."
  krnLog "Mapping VFS..."
  mkdir $drives/vfs
  krnLog "Creating vfs/dev..."
  mkdir $drives/vfs/dev
  krnLog "Adding null device..."
  ln -s /dev/null $drives/vfs/dev/null # Link to POSIX null device.
  krnLog "Virtual file system initialized."
}

function krnLogInit() {
  deleteFile hd/system/logs/kernel.log
  createFile hd/system/logs/kernel.log
}

# Log the first argument to the kernel log.
function krnLog() {
  open hd/system/logs/kernel.log
  echo $1 >> $return
}

# TODO: Figure out what should go in here and what should go in SysCall.lib.
